version: '3'

services:
  employees-postgres:
    image: postgres
    ports:
      - '5433:5432'
    environment:
      POSTGRES_DB: employees
      POSTGRES_USER: employees
      POSTGRES_PASSWORD: employees

  employees:
    image: employees
    ports: 
      - '5001:5000'
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://employees:employees@employees-postgres/employees